version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
